version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000  
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=Anush123~
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=44frt@Ey6sferr77779rwrw6474646f78sf787e97w9f9e7f97s9f7s9f7s9f7s9f7979sf79fsfsfdf
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=300  
    